<script setup lang="ts">
import { computed, ref, watch } from 'vue'

// Three-pane documentation shell (sidebar · content · on-this-page), with a
// sticky top bar and a mobile drawer for the sidebar. The center content is the
// page itself (rendered by pages/docs/[...slug].vue through the <slot/>).
const route = useRoute()

// The page is also queried in the catch-all page component under this exact key,
// so useAsyncData dedupes — this read is free and gives us the TOC + title.
const { data: page } = await useAsyncData(`docs:${route.path}`, () =>
  queryCollection('docs').path(route.path).first(),
)

const tocLinks = computed(() => (page.value as any)?.body?.toc?.links ?? [])

// Mobile sidebar drawer.
const drawerOpen = ref(false)
watch(
  () => route.path,
  () => {
    drawerOpen.value = false
  },
)

// Every page has a raw Markdown twin (generated by modules/generated-surfaces.ts).
// Advertise it in <head> as rel=alternate so agents/LLMs discover it in the first
// lines of the HTML (they skim the head, not the whole document), and surface a
// visible link at the top of the page too.
const mdPath = computed(() =>
  route.path === '/docs' ? '/docs.md' : route.path.replace(/\/+$/, '') + '.md',
)
useHead({
  link: [
    {
      rel: 'alternate',
      type: 'text/markdown',
      href: () => mdPath.value,
      title: 'This page as Markdown (for LLMs and agents)',
    },
  ],
})
</script>

<template>
  <div class="docs-root">
    <!-- The sitewide header, plus the two things only docs needs: the "Docs"
         badge and the drawer toggle. -->
    <SiteHeader
      v-model:menu-open="drawerOpen"
      brand-tag="Docs"
      menu-controls="docs-sidebar-drawer"
      menu-toggle
      wide
    />

    <!-- Mobile drawer scrim -->
    <div v-if="drawerOpen" class="docs-scrim" @click="drawerOpen = false" />

    <div class="docs-grid">
      <!-- Left sidebar (becomes a drawer under the lg breakpoint) -->
      <aside id="docs-sidebar-drawer" class="docs-aside" :class="{ 'is-open': drawerOpen }">
        <div class="docs-aside__inner">
          <DocsSidebar @navigate="drawerOpen = false" />
        </div>
      </aside>

      <!-- Center content -->
      <main class="docs-main">
        <div class="docs-md-cta">
          <a :href="mdPath" class="docs-md-link" title="Read this page as plain Markdown — handy for LLMs and agents">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M4 7h16M4 12h10M4 17h16" />
            </svg>
            View as Markdown
          </a>
        </div>
        <article class="docs-prose">
          <slot />
        </article>
        <!-- The marketing footer does not mount in this shell, so docs pages carried
             no ownership, legal, or contact line at all. This colophon is that line. -->
        <footer class="docs-colophon">
          <p>
            BitterClip is a product of
            <a href="https://company.sheetgenius.com">SheetGenius, Inc.</a>
          </p>
          <p class="docs-colophon__links">
            <NuxtLink to="/privacy">Privacy</NuxtLink>
            <span aria-hidden="true">·</span>
            <NuxtLink to="/terms">Terms</NuxtLink>
            <span aria-hidden="true">·</span>
            <a href="mailto:hello@bitterclip.com?subject=BitterClip%20support">hello@bitterclip.com</a>
            <span aria-hidden="true">·</span>
            <span>© 2026 SheetGenius, Inc.</span>
          </p>
        </footer>
      </main>

      <!-- Right rail: on this page -->
      <aside class="docs-rail">
        <DocsToc :links="tocLinks" />
      </aside>
    </div>
  </div>
</template>

<style scoped>
.docs-colophon {
  margin-top: 4rem;
  padding-top: 1.25rem;
  border-top: 1px solid rgba(255, 255, 255, 0.08);
  font-size: 0.75rem;
  line-height: 1.6;
  color: #8b8b93;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: 0.5rem 1.5rem;
}

.docs-colophon p {
  margin: 0;
}

.docs-colophon .docs-colophon__links {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
}

.docs-colophon a {
  color: #b6b6bd;
  text-decoration: none;
}

.docs-colophon a:hover {
  color: #f28f84;
}

.docs-root {
  position: relative;
  min-height: 100vh;
  background-color: var(--bitter-bg);
  color: #f4f4f5;
}


/* The header itself lives in components/SiteHeader.vue — shared with the
   marketing layout, so nothing about the bar is styled here. */

/* ---- Three-pane grid ---- */
/* No z-index here: it would open a stacking context that traps .docs-aside's
   drawer z-index inside it, leaving the open mobile drawer under its own scrim.
   Tree order already paints this above the inert background, which is inert. */
.docs-grid {
  position: relative;
  display: grid;
  grid-template-columns: 16rem minmax(0, 1fr) 15rem;
  gap: 2.5rem;
  max-width: 90rem;
  margin: 0 auto;
  padding: 0 1.5rem;
  align-items: start;
}

.docs-aside {
  position: sticky;
  top: 4.2rem;
  height: calc(100vh - 4.2rem);
  overflow-y: auto;
  padding-top: 2rem;
}
.docs-aside__inner {
  min-height: 100%;
}

.docs-main {
  min-width: 0;
  padding: 2.5rem 0 5rem;
}
.docs-md-cta {
  display: flex;
  justify-content: flex-end;
  margin-bottom: 0.75rem;
}
.docs-md-link {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-family: var(--font-mono);
  font-size: 0.72rem;
  letter-spacing: 0.02em;
  color: rgba(244, 244, 245, 0.55);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 9999px;
  padding: 0.25rem 0.7rem;
  transition: color 0.18s, border-color 0.18s, background 0.18s;
}
.docs-md-link:hover {
  color: #f28f84;
  border-color: rgba(242, 143, 132, 0.4);
  background: rgba(242, 143, 132, 0.06);
}
.docs-md-link svg {
  width: 0.9rem;
  height: 0.9rem;
}

.docs-rail {
  padding-top: 2.5rem;
}

.docs-scrim {
  display: none;
}

/* ---- Responsive ---- */
@media (max-width: 1100px) {
  .docs-grid {
    grid-template-columns: 15rem minmax(0, 1fr);
  }
  .docs-rail {
    display: none;
  }
}

@media (max-width: 820px) {
  .docs-grid {
    grid-template-columns: minmax(0, 1fr);
    padding: 0 1.25rem;
  }
  /* Above the header's z-50 so the open drawer and its scrim cover the bar,
     as they did when the header sat at z-40. */
  .docs-aside {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 60;
    width: 18rem;
    max-width: 85vw;
    height: 100vh;
    padding: 5rem 1.25rem 2rem;
    background: rgba(8, 9, 9, 0.97);
    backdrop-filter: blur(20px);
    border-right: 1px solid rgba(255, 255, 255, 0.06);
    transform: translateX(-105%);
    transition: transform 0.28s cubic-bezier(0.16, 1, 0.3, 1);
  }
  .docs-aside.is-open {
    transform: translateX(0);
  }
  .docs-scrim {
    display: block;
    position: fixed;
    inset: 0;
    z-index: 55;
    background: rgba(0, 0, 0, 0.5);
    backdrop-filter: blur(2px);
  }
}

@media (prefers-reduced-motion: reduce) {
  .docs-aside {
    transition: none !important;
  }
}
</style>
